#ifndef _NYAUX_SYSCALL_H
#define _NYAUX_SYSCALL_H

#define SYSCALL_EXIT 0
#define SYSCALL_DEBUG 1
#define SYSCALL_SETFSBASE 2
#define SYSCALL_MMAP 3
#define SYSCALL_OPENAT 4
#define SYSCALL_READ 5
#define SYSCALL_SEEK 6
#define SYSCALL_CLOSE 7
#define SYSCALL_ISATTY 8
#define SYSCALL_WRITE 9
#define SYSCALL_IOCTL 10
#define SYSCALL_DUP 11
#define SYSCALL_FSTAT 12
#define SYSCALL_GETCWD 13
#define SYSCALL_FORK 14
#define SYSCALL_WAITPID 15
#define SYSCALL_GETPID 16
#define SYSCALL_FREE 17
#define SYSCALL_EXECVE 18
#define SYSCALL_FACCESSAT 19
#endif