#ifndef _ABIBITS_LIMITS_H
#define _ABIBITS_LIMITS_H

#define __MLIBC_IOV_MAX 1024
#define __MLIBC_LOGIN_NAME_MAX 256
#define __MLIBC_HOST_NAME_MAX 64
#define __MLIBC_NAME_MAX 255
#define __MLIBC_OPEN_MAX 256

#endif /*_ABIBITS_LIMITS_H */
