fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: 336fdd7c3cab698ead0b1c95157b9e74d3906b62
    hooks:
      - id: clang-format
        additional_dependencies: [clang-format==19.1.3]
        args: ["-i"]
        exclude: >
          (?x)^(
            options/ansi/musl-generic-math/.*|
            options/ansi/generic/complex/.*|
            options/posix/musl-generic-regex/.*
          )
        # Only enable on Managarm sysdeps for now.
        files:
          sysdeps/managarm/
