
#ifndef _NL_ITEM_H
#define _NL_ITEM_H

#ifdef __cplusplus
extern "C" {
#endif

#include <bits/locale.h>

typedef int nl_item;

#define __NL_ITEM(category, num) ((category << 16) | (num & 0xFFFF))

enum { /* NOLINT(readability-enum-initial-value) */
	_NL_CTYPE_CLASS = __NL_ITEM(LC_CTYPE, 0),
	_NL_CTYPE_TOUPPER,
	_NL_CTYPE_GAP1,
	_NL_CTYPE_TOLOWER,
	_NL_CTYPE_GAP2,
	_NL_CTYPE_CLASS32,
	_NL_CTYPE_GAP3,
	_NL_CTYPE_GAP4,
	_NL_CTYPE_GAP5,
	_NL_CTYPE_GAP6,
	_NL_CTYPE_CLASS_NAMES,
	_NL_CTYPE_MAP_NAMES,
	_NL_CTYPE_WIDTH,
	_NL_CTYPE_MB_CUR_MAX,
	_NL_CTYPE_CODESET_NAME,
	CODESET = _NL_CTYPE_CODESET_NAME,
#define CODESET CODESET
	_NL_CTYPE_TOUPPER32,
	_NL_CTYPE_TOLOWER32,
	_NL_CTYPE_CLASS_OFFSET,
	_NL_CTYPE_MAP_OFFSET,
	_NL_CTYPE_INDIGITS_MB_LEN,
	_NL_CTYPE_INDIGITS0_MB,
	_NL_CTYPE_INDIGITS1_MB,
	_NL_CTYPE_INDIGITS2_MB,
	_NL_CTYPE_INDIGITS3_MB,
	_NL_CTYPE_INDIGITS4_MB,
	_NL_CTYPE_INDIGITS5_MB,
	_NL_CTYPE_INDIGITS6_MB,
	_NL_CTYPE_INDIGITS7_MB,
	_NL_CTYPE_INDIGITS8_MB,
	_NL_CTYPE_INDIGITS9_MB,
	_NL_CTYPE_INDIGITS_WC_LEN,
	_NL_CTYPE_INDIGITS0_WC,
	_NL_CTYPE_INDIGITS1_WC,
	_NL_CTYPE_INDIGITS2_WC,
	_NL_CTYPE_INDIGITS3_WC,
	_NL_CTYPE_INDIGITS4_WC,
	_NL_CTYPE_INDIGITS5_WC,
	_NL_CTYPE_INDIGITS6_WC,
	_NL_CTYPE_INDIGITS7_WC,
	_NL_CTYPE_INDIGITS8_WC,
	_NL_CTYPE_INDIGITS9_WC,
	_NL_CTYPE_OUTDIGIT0_MB,
	_NL_CTYPE_OUTDIGIT1_MB,
	_NL_CTYPE_OUTDIGIT2_MB,
	_NL_CTYPE_OUTDIGIT3_MB,
	_NL_CTYPE_OUTDIGIT4_MB,
	_NL_CTYPE_OUTDIGIT5_MB,
	_NL_CTYPE_OUTDIGIT6_MB,
	_NL_CTYPE_OUTDIGIT7_MB,
	_NL_CTYPE_OUTDIGIT8_MB,
	_NL_CTYPE_OUTDIGIT9_MB,
	_NL_CTYPE_OUTDIGIT0_WC,
	_NL_CTYPE_OUTDIGIT1_WC,
	_NL_CTYPE_OUTDIGIT2_WC,
	_NL_CTYPE_OUTDIGIT3_WC,
	_NL_CTYPE_OUTDIGIT4_WC,
	_NL_CTYPE_OUTDIGIT5_WC,
	_NL_CTYPE_OUTDIGIT6_WC,
	_NL_CTYPE_OUTDIGIT7_WC,
	_NL_CTYPE_OUTDIGIT8_WC,
	_NL_CTYPE_OUTDIGIT9_WC,
	_NL_CTYPE_TRANSLIT_TAB_SIZE,
	_NL_CTYPE_TRANSLIT_FROM_IDX,
	_NL_CTYPE_TRANSLIT_FROM_TBL,
	_NL_CTYPE_TRANSLIT_TO_IDX,
	_NL_CTYPE_TRANSLIT_TO_TBL,
	_NL_CTYPE_TRANSLIT_DEFAULT_MISSING_LEN,
	_NL_CTYPE_TRANSLIT_DEFAULT_MISSING,
	_NL_CTYPE_TRANSLIT_IGNORE_LEN,
	_NL_CTYPE_TRANSLIT_IGNORE,
	_NL_CTYPE_MAP_TO_NONASCII,
	_NL_CTYPE_NONASCII_CASE,
	_NL_CTYPE_EXTRA_MAP_1,
	_NL_CTYPE_EXTRA_MAP_2,
	_NL_CTYPE_EXTRA_MAP_3,
	_NL_CTYPE_EXTRA_MAP_4,
	_NL_CTYPE_EXTRA_MAP_5,
	_NL_CTYPE_EXTRA_MAP_6,
	_NL_CTYPE_EXTRA_MAP_7,
	_NL_CTYPE_EXTRA_MAP_8,
	_NL_CTYPE_EXTRA_MAP_9,
	_NL_CTYPE_EXTRA_MAP_10,
	_NL_CTYPE_EXTRA_MAP_11,
	_NL_CTYPE_EXTRA_MAP_12,
	_NL_CTYPE_EXTRA_MAP_13,
	_NL_CTYPE_EXTRA_MAP_14,
	_NL_CTYPE_EXTRA_MAP_15,
	_NL_CTYPE_EXTRA_MAP_16,
	_NL_NUM_LC_CTYPE,

	__DECIMAL_POINT = __NL_ITEM(LC_NUMERIC, 0),
#ifdef _GNU_SOURCE
#define DECIMAL_POINT __DECIMAL_POINT
#endif
	RADIXCHAR = __DECIMAL_POINT,
#define RADIXCHAR RADIXCHAR
	__THOUSANDS_SEP,
#ifdef _GNU_SOURCE
#define THOUSANDS_SEP __THOUSANDS_SEP
#endif
	THOUSEP = __THOUSANDS_SEP,
#define THOUSEP THOUSEP
	__GROUPING,
#ifdef _GNU_SOURCE
#define GROUPING __GROUPING
#endif
	_NL_NUMERIC_DECIMAL_POINT_WC,
	_NL_NUMERIC_THOUSANDS_SEP_WC,
	_NL_NUMERIC_CODESET,
	_NL_NUM_LC_NUMERIC,

	ABDAY_1 = __NL_ITEM(LC_TIME, 0),
#define ABDAY_1 ABDAY_1
	ABDAY_2,
#define ABDAY_2 ABDAY_2
	ABDAY_3,
#define ABDAY_3 ABDAY_3
	ABDAY_4,
#define ABDAY_4 ABDAY_4
	ABDAY_5,
#define ABDAY_5 ABDAY_5
	ABDAY_6,
#define ABDAY_6 ABDAY_6
	ABDAY_7,
#define ABDAY_7 ABDAY_7
	DAY_1,
#define DAY_1 DAY_1
	DAY_2,
#define DAY_2 DAY_2
	DAY_3,
#define DAY_3 DAY_3
	DAY_4,
#define DAY_4 DAY_4
	DAY_5,
#define DAY_5 DAY_5
	DAY_6,
#define DAY_6 DAY_6
	DAY_7,
#define DAY_7 DAY_7
	ABMON_1,
#define ABMON_1 ABMON_1
	ABMON_2,
#define ABMON_2 ABMON_2
	ABMON_3,
#define ABMON_3 ABMON_3
	ABMON_4,
#define ABMON_4 ABMON_4
	ABMON_5,
#define ABMON_5 ABMON_5
	ABMON_6,
#define ABMON_6 ABMON_6
	ABMON_7,
#define ABMON_7 ABMON_7
	ABMON_8,
#define ABMON_8 ABMON_8
	ABMON_9,
#define ABMON_9 ABMON_9
	ABMON_10,
#define ABMON_10 ABMON_10
	ABMON_11,
#define ABMON_11 ABMON_11
	ABMON_12,
#define ABMON_12 ABMON_12
	MON_1,
#define MON_1 MON_1
	MON_2,
#define MON_2 MON_2
	MON_3,
#define MON_3 MON_3
	MON_4,
#define MON_4 MON_4
	MON_5,
#define MON_5 MON_5
	MON_6,
#define MON_6 MON_6
	MON_7,
#define MON_7 MON_7
	MON_8,
#define MON_8 MON_8
	MON_9,
#define MON_9 MON_9
	MON_10,
#define MON_10 MON_10
	MON_11,
#define MON_11 MON_11
	MON_12,
#define MON_12 MON_12
	AM_STR,
#define AM_STR AM_STR
	PM_STR,
#define PM_STR PM_STR

	D_T_FMT,
#define D_T_FMT D_T_FMT
	D_FMT,
#define D_FMT D_FMT
	T_FMT,
#define T_FMT T_FMT
	T_FMT_AMPM,
#define T_FMT_AMPM T_FMT_AMPM

	ERA,
#define ERA ERA
	__ERA_YEAR,
#ifdef _GNU_SOURCE
#define ERA_YEAR __ERA_YEAR
#endif
	ERA_D_FMT,
#define ERA_D_FMT ERA_D_FMT
	ALT_DIGITS,
#define ALT_DIGITS ALT_DIGITS
	ERA_D_T_FMT,
#define ERA_D_T_FMT ERA_D_T_FMT
	ERA_T_FMT,
#define ERA_T_FMT ERA_T_FMT
	_NL_TIME_ERA_NUM_ENTRIES,
	_NL_TIME_ERA_ENTRIES,

	_NL_WABDAY_1,
	_NL_WABDAY_2,
	_NL_WABDAY_3,
	_NL_WABDAY_4,
	_NL_WABDAY_5,
	_NL_WABDAY_6,
	_NL_WABDAY_7,

	_NL_WDAY_1,
	_NL_WDAY_2,
	_NL_WDAY_3,
	_NL_WDAY_4,
	_NL_WDAY_5,
	_NL_WDAY_6,
	_NL_WDAY_7,

	_NL_WABMON_1,
	_NL_WABMON_2,
	_NL_WABMON_3,
	_NL_WABMON_4,
	_NL_WABMON_5,
	_NL_WABMON_6,
	_NL_WABMON_7,
	_NL_WABMON_8,
	_NL_WABMON_9,
	_NL_WABMON_10,
	_NL_WABMON_11,
	_NL_WABMON_12,

	_NL_WMON_1,
	_NL_WMON_2,
	_NL_WMON_3,
	_NL_WMON_4,
	_NL_WMON_5,
	_NL_WMON_6,
	_NL_WMON_7,
	_NL_WMON_8,
	_NL_WMON_9,
	_NL_WMON_10,
	_NL_WMON_11,
	_NL_WMON_12,

	_NL_WAM_STR,
	_NL_WPM_STR,

	_NL_WD_T_FMT,
	_NL_WD_FMT,
	_NL_WT_FMT,
	_NL_WT_FMT_AMPM,

	_NL_WERA_YEAR,
	_NL_WERA_D_FMT,
	_NL_WALT_DIGITS,
	_NL_WERA_D_T_FMT,
	_NL_WERA_T_FMT,

	_NL_TIME_WEEK_NDAYS,
	_NL_TIME_WEEK_1STDAY,
	_NL_TIME_WEEK_1STWEEK,
	_NL_TIME_FIRST_WEEKDAY,
	_NL_TIME_FIRST_WORKDAY,
	_NL_TIME_CAL_DIRECTION,
	_NL_TIME_TIMEZONE,

	_DATE_FMT,
#define _DATE_FMT _DATE_FMT
	_NL_W_DATE_FMT,

	_NL_TIME_CODESET,

	__ALTMON_1,
	__ALTMON_2,
	__ALTMON_3,
	__ALTMON_4,
	__ALTMON_5,
	__ALTMON_6,
	__ALTMON_7,
	__ALTMON_8,
	__ALTMON_9,
	__ALTMON_10,
	__ALTMON_11,
	__ALTMON_12,
#ifdef _GNU_SOURCE
#define ALTMON_1 __ALTMON_1
#define ALTMON_2 __ALTMON_2
#define ALTMON_3 __ALTMON_3
#define ALTMON_4 __ALTMON_4
#define ALTMON_5 __ALTMON_5
#define ALTMON_6 __ALTMON_6
#define ALTMON_7 __ALTMON_7
#define ALTMON_8 __ALTMON_8
#define ALTMON_9 __ALTMON_9
#define ALTMON_10 __ALTMON_10
#define ALTMON_11 __ALTMON_11
#define ALTMON_12 __ALTMON_12
#endif

	_NL_WALTMON_1,
	_NL_WALTMON_2,
	_NL_WALTMON_3,
	_NL_WALTMON_4,
	_NL_WALTMON_5,
	_NL_WALTMON_6,
	_NL_WALTMON_7,
	_NL_WALTMON_8,
	_NL_WALTMON_9,
	_NL_WALTMON_10,
	_NL_WALTMON_11,
	_NL_WALTMON_12,

	_NL_ABALTMON_1,
	_NL_ABALTMON_2,
	_NL_ABALTMON_3,
	_NL_ABALTMON_4,
	_NL_ABALTMON_5,
	_NL_ABALTMON_6,
	_NL_ABALTMON_7,
	_NL_ABALTMON_8,
	_NL_ABALTMON_9,
	_NL_ABALTMON_10,
	_NL_ABALTMON_11,
	_NL_ABALTMON_12,

	_NL_WABALTMON_1,
	_NL_WABALTMON_2,
	_NL_WABALTMON_3,
	_NL_WABALTMON_4,
	_NL_WABALTMON_5,
	_NL_WABALTMON_6,
	_NL_WABALTMON_7,
	_NL_WABALTMON_8,
	_NL_WABALTMON_9,
	_NL_WABALTMON_10,
	_NL_WABALTMON_11,
	_NL_WABALTMON_12,

	_NL_NUM_LC_TIME,

	_NL_COLLATE_NRULES = __NL_ITEM(LC_COLLATE, 0),
	_NL_COLLATE_RULESETS,
	_NL_COLLATE_TABLEMB,
	_NL_COLLATE_WEIGHTMB,
	_NL_COLLATE_EXTRAMB,
	_NL_COLLATE_INDIRECTMB,
	_NL_COLLATE_GAP1,
	_NL_COLLATE_GAP2,
	_NL_COLLATE_GAP3,
	_NL_COLLATE_TABLEWC,
	_NL_COLLATE_WEIGHTWC,
	_NL_COLLATE_EXTRAWC,
	_NL_COLLATE_INDIRECTWC,
	_NL_COLLATE_SYMB_HASH_SIZEMB,
	_NL_COLLATE_SYMB_TABLEMB,
	_NL_COLLATE_SYMB_EXTRAMB,
	_NL_COLLATE_COLLSEQMB,
	_NL_COLLATE_COLLSEQWC,
	_NL_COLLATE_CODESET,
	_NL_NUM_LC_COLLATE,

	__INT_CURR_SYMBOL = __NL_ITEM(LC_MONETARY, 0),
#ifdef _GNU_SOURCE
#define INT_CURR_SYMBOL __INT_CURR_SYMBOL
#endif
	__CURRENCY_SYMBOL,
#ifdef _GNU_SOURCE
#define CURRENCY_SYMBOL __CURRENCY_SYMBOL
#endif
	__MON_DECIMAL_POINT,
#ifdef _GNU_SOURCE
#define MON_DECIMAL_POINT __MON_DECIMAL_POINT
#endif
	__MON_THOUSANDS_SEP,
#ifdef _GNU_SOURCE
#define MON_THOUSANDS_SEP __MON_THOUSANDS_SEP
#endif
	__MON_GROUPING,
#ifdef _GNU_SOURCE
#define MON_GROUPING __MON_GROUPING
#endif
	__POSITIVE_SIGN,
#ifdef _GNU_SOURCE
#define POSITIVE_SIGN __POSITIVE_SIGN
#endif
	__NEGATIVE_SIGN,
#ifdef _GNU_SOURCE
#define NEGATIVE_SIGN __NEGATIVE_SIGN
#endif
	__INT_FRAC_DIGITS,
#ifdef _GNU_SOURCE
#define INT_FRAC_DIGITS __INT_FRAC_DIGITS
#endif
	__FRAC_DIGITS,
#ifdef _GNU_SOURCE
#define FRAC_DIGITS __FRAC_DIGITS
#endif
	__P_CS_PRECEDES,
#ifdef _GNU_SOURCE
#define P_CS_PRECEDES __P_CS_PRECEDES
#endif
	__P_SEP_BY_SPACE,
#ifdef _GNU_SOURCE
#define P_SEP_BY_SPACE __P_SEP_BY_SPACE
#endif
	__N_CS_PRECEDES,
#ifdef _GNU_SOURCE
#define N_CS_PRECEDES __N_CS_PRECEDES
#endif
	__N_SEP_BY_SPACE,
#ifdef _GNU_SOURCE
#define N_SEP_BY_SPACE __N_SEP_BY_SPACE
#endif
	__P_SIGN_POSN,
#ifdef _GNU_SOURCE
#define P_SIGN_POSN __P_SIGN_POSN
#endif
	__N_SIGN_POSN,
#ifdef _GNU_SOURCE
#define N_SIGN_POSN __N_SIGN_POSN
#endif
	_NL_MONETARY_CRNCYSTR,
#define CRNCYSTR _NL_MONETARY_CRNCYSTR
	__INT_P_CS_PRECEDES,
#ifdef _GNU_SOURCE
#define INT_P_CS_PRECEDES __INT_P_CS_PRECEDES
#endif
	__INT_P_SEP_BY_SPACE,
#ifdef _GNU_SOURCE
#define INT_P_SEP_BY_SPACE __INT_P_SEP_BY_SPACE
#endif
	__INT_N_CS_PRECEDES,
#ifdef _GNU_SOURCE
#define INT_N_CS_PRECEDES __INT_N_CS_PRECEDES
#endif
	__INT_N_SEP_BY_SPACE,
#ifdef _GNU_SOURCE
#define INT_N_SEP_BY_SPACE __INT_N_SEP_BY_SPACE
#endif
	__INT_P_SIGN_POSN,
#ifdef _GNU_SOURCE
#define INT_P_SIGN_POSN __INT_P_SIGN_POSN
#endif
	__INT_N_SIGN_POSN,
#ifdef _GNU_SOURCE
#define INT_N_SIGN_POSN __INT_N_SIGN_POSN
#endif
	_NL_MONETARY_DUO_INT_CURR_SYMBOL,
	_NL_MONETARY_DUO_CURRENCY_SYMBOL,
	_NL_MONETARY_DUO_INT_FRAC_DIGITS,
	_NL_MONETARY_DUO_FRAC_DIGITS,
	_NL_MONETARY_DUO_P_CS_PRECEDES,
	_NL_MONETARY_DUO_P_SEP_BY_SPACE,
	_NL_MONETARY_DUO_N_CS_PRECEDES,
	_NL_MONETARY_DUO_N_SEP_BY_SPACE,
	_NL_MONETARY_DUO_INT_P_CS_PRECEDES,
	_NL_MONETARY_DUO_INT_P_SEP_BY_SPACE,
	_NL_MONETARY_DUO_INT_N_CS_PRECEDES,
	_NL_MONETARY_DUO_INT_N_SEP_BY_SPACE,
	_NL_MONETARY_DUO_P_SIGN_POSN,
	_NL_MONETARY_DUO_N_SIGN_POSN,
	_NL_MONETARY_DUO_INT_P_SIGN_POSN,
	_NL_MONETARY_DUO_INT_N_SIGN_POSN,
	_NL_MONETARY_UNO_VALID_FROM,
	_NL_MONETARY_UNO_VALID_TO,
	_NL_MONETARY_DUO_VALID_FROM,
	_NL_MONETARY_DUO_VALID_TO,
	_NL_MONETARY_CONVERSION_RATE,
	_NL_MONETARY_DECIMAL_POINT_WC,
	_NL_MONETARY_THOUSANDS_SEP_WC,
	_NL_MONETARY_CODESET,
	_NL_NUM_LC_MONETARY,

	__YESEXPR = __NL_ITEM(LC_MESSAGES, 0),
#define YESEXPR __YESEXPR
	__NOEXPR,
#define NOEXPR __NOEXPR
	__YESSTR,
#ifdef _GNU_SOURCE
#define YESSTR __YESSTR
#endif
	__NOSTR,
#ifdef _GNU_SOURCE
#define NOSTR __NOSTR
#endif
	_NL_MESSAGES_CODESET,
	_NL_NUM_LC_MESSAGES,

	_NL_PAPER_HEIGHT = __NL_ITEM(LC_PAPER, 0),
	_NL_PAPER_WIDTH,
	_NL_PAPER_CODESET,
	_NL_NUM_LC_PAPER,

	_NL_NAME_NAME_FMT = __NL_ITEM(LC_NAME, 0),
	_NL_NAME_NAME_GEN,
	_NL_NAME_NAME_MR,
	_NL_NAME_NAME_MRS,
	_NL_NAME_NAME_MISS,
	_NL_NAME_NAME_MS,
	_NL_NAME_CODESET,
	_NL_NUM_LC_NAME,

	_NL_ADDRESS_POSTAL_FMT = __NL_ITEM(LC_ADDRESS, 0),
	_NL_ADDRESS_COUNTRY_NAME,
	_NL_ADDRESS_COUNTRY_POST,
	_NL_ADDRESS_COUNTRY_AB2,
	_NL_ADDRESS_COUNTRY_AB3,
	_NL_ADDRESS_COUNTRY_CAR,
	_NL_ADDRESS_COUNTRY_NUM,
	_NL_ADDRESS_COUNTRY_ISBN,
	_NL_ADDRESS_LANG_NAME,
	_NL_ADDRESS_LANG_AB,
	_NL_ADDRESS_LANG_TERM,
	_NL_ADDRESS_LANG_LIB,
	_NL_ADDRESS_CODESET,
	_NL_NUM_LC_ADDRESS,

	_NL_TELEPHONE_TEL_INT_FMT = __NL_ITEM(LC_TELEPHONE, 0),
	_NL_TELEPHONE_TEL_DOM_FMT,
	_NL_TELEPHONE_INT_SELECT,
	_NL_TELEPHONE_INT_PREFIX,
	_NL_TELEPHONE_CODESET,
	_NL_NUM_LC_TELEPHONE,

	_NL_MEASUREMENT_MEASUREMENT = __NL_ITEM(LC_MEASUREMENT, 0),
	_NL_MEASUREMENT_CODESET,
	_NL_NUM_LC_MEASUREMENT,

	_NL_IDENTIFICATION_TITLE = __NL_ITEM(LC_IDENTIFICATION, 0),
	_NL_IDENTIFICATION_SOURCE,
	_NL_IDENTIFICATION_ADDRESS,
	_NL_IDENTIFICATION_CONTACT,
	_NL_IDENTIFICATION_EMAIL,
	_NL_IDENTIFICATION_TEL,
	_NL_IDENTIFICATION_FAX,
	_NL_IDENTIFICATION_LANGUAGE,
	_NL_IDENTIFICATION_TERRITORY,
	_NL_IDENTIFICATION_AUDIENCE,
	_NL_IDENTIFICATION_APPLICATION,
	_NL_IDENTIFICATION_ABBREVIATION,
	_NL_IDENTIFICATION_REVISION,
	_NL_IDENTIFICATION_DATE,
	_NL_IDENTIFICATION_CATEGORY,
	_NL_IDENTIFICATION_CODESET,
	_NL_NUM_LC_IDENTIFICATION
};

#ifdef __cplusplus
}
#endif

#endif /* _NL_ITEM_H */

