#ifndef _MLIBC_INTERNAL_PTHREAD_SIZES_H
#define _MLIBC_INTERNAL_PTHREAD_SIZES_H

#define __MLIBC_THREAD_BARRIER_SIZE 64
#define __MLIBC_THREAD_MUTEX_SIZE 64
#define __MLIBC_THREAD_COND_SIZE 64
#define __MLIBC_THREAD_RWLOCK_SIZE 64
#define __MLIBC_THREAD_ONCE_SIZE 4
#define __MLIBC_THREAD_SPINLOCK_SIZE 4

#endif /* _MLIBC_INTERNAL_PTHREAD_SIZES_H */
