#pragma once

#define UCONTEXT_GREGS_OFFSET 40

#define UCONTEXT_OFFSET_R8 (UCONTEXT_GREGS_OFFSET + 0)
#define UCONTEXT_OFFSET_R9 (UCONTEXT_GREGS_OFFSET + 8)
#define UCONTEXT_OFFSET_R10 (UCONTEXT_GREGS_OFFSET + 16)
#define UCONTEXT_OFFSET_R11 (UCONTEXT_GREGS_OFFSET + 24)
#define UCONTEXT_OFFSET_R12 (UCONTEXT_GREGS_OFFSET + 32)
#define UCONTEXT_OFFSET_R13 (UCONTEXT_GREGS_OFFSET + 40)
#define UCONTEXT_OFFSET_R14 (UCONTEXT_GREGS_OFFSET + 48)
#define UCONTEXT_OFFSET_R15 (UCONTEXT_GREGS_OFFSET + 56)
#define UCONTEXT_OFFSET_RDI (UCONTEXT_GREGS_OFFSET + 64)
#define UCONTEXT_OFFSET_RSI (UCONTEXT_GREGS_OFFSET + 72)
#define UCONTEXT_OFFSET_RBP (UCONTEXT_GREGS_OFFSET + 80)
#define UCONTEXT_OFFSET_RBX (UCONTEXT_GREGS_OFFSET + 88)
#define UCONTEXT_OFFSET_RDX (UCONTEXT_GREGS_OFFSET + 96)
#define UCONTEXT_OFFSET_RAX (UCONTEXT_GREGS_OFFSET + 104)
#define UCONTEXT_OFFSET_RCX (UCONTEXT_GREGS_OFFSET + 112)
#define UCONTEXT_OFFSET_RSP (UCONTEXT_GREGS_OFFSET + 120)
#define UCONTEXT_OFFSET_RIP (UCONTEXT_GREGS_OFFSET + 128)
