#pragma once

#include <mlibc/sysdep-signatures.hpp>

namespace mlibc {

struct BadgerOSSysdepTags :
    /* Base sysdeps */
    LibcLog,
    LibcPanic,
    // FutexTid,
    AnonAllocate,
    AnonFree,
    Stat,
    VmMap,
    VmUnmap,
    VmProtect,
    TcbSet,
#ifdef __riscv
// RiscvHwprobe,
#endif // __riscv

    /* ANSI sysdeps */
    Exit,
    // ThreadExit,
    // PrepareStack,
    // Clone,
    FutexWait,
    FutexWake,
    Open,
    // Flock,
    OpenDir,
    ReadEntries,
    Read,
    Write,
    // Pread,
    Seek,
    Close,
    ClockGet,
    // ClockSet,
    // ClockGetres,
    // Sleep,
    Isatty,
    Rmdir,
    Unlinkat,
    Rename,
    // FdToPath,
    Sigprocmask,
    Sigaction,
    Fork,
    Waitpid,
    Execve,
    // Yield,
    GetPid,
    Kill,

    /* Building RTLD */
    // VmReadahead,

    /* POSIX sysdeps */
    // Readv,
    // Writev,
    // Pwrite,
    // Access,
    // Faccessat,
    Dup,
    Dup2,
    // Statvfs,
    // Fstatvfs,
    // Readlink,
    // Readlinkat,
    // Truncate,
    // Ftruncate,
    // Fallocate,
    // Openat,
    // Socket,
    // MsgSend,
    // Sendto,
    // MsgRecv,
    // Recvfrom,
    // Listen,
    GetGid,
    GetEgid,
    GetUid,
    GetEuid,
    GetTid,
    GetPpid,
    GetPgid,
    GetSid,
    // SetPgid,
    // SetUid,
    // SetEuid,
    // SetGid,
    // SetEgid,
    // GetGroups,
    // Fexecve,
    // Pselect,
    // GetRusage,
    // GetRlimit,
    // SetRlimit,
    // GetPriority,
    // SetPriority,
    // GetSchedparam,
    // SetSchedparam,
    // GetScheduler,
    // SetScheduler,
    // GetParam,
    // SetParam,
    // GetMaxPriority,
    // GetMinPriority,
    GetCwd,
    Chdir,
    Fchdir,
    // Chroot,
    Mkdir,
    Mkdirat,
    Link,
    Linkat,
    Symlink,
    Symlinkat,
    Renameat,
    Fcntl,
    // Ttyname,
    // Fadvise,
    // Sync,
    // Fsync,
    // Fdatasync,
    // Chmod,
    // Fchmod,
    // Fchmodat,
    // Utimensat,
    // Mlock,
    // Munlock,
    // Mlockall,
    // Munlockall,
    // Mincore,
    // VmRemap,
    // SetSid,
    Tcgetattr,
    Tcsetattr,
    // Tcsendbreak,
    // Tcflow,
    // Tcflush,
    // Tcdrain,
    // Tcgetwinsize,
    // Tcsetwinsize,
    // Pipe,
    // Socketpair,
    // Poll,
    // Ppoll,
    // Ioctl,
    // PosixDevctl,
    // GetSockopt,
    // SetSockopt,
    // Shutdown,
    // Sockatmark,
    ThreadSigmask,
    // Sigtimedwait,
    // Accept,
    // Bind,
    // Connect,
    // Sockname,
    // Peername,
    // GetHostname,
    // SetHostname,
    // Mkfifoat,
    // GetEntropy,
    // Mknodat,
    // Umask,
    // BeforeCancellableSyscall,
    // Tgkill,
    // Fchownat,
    // Sigaltstack,
    // Sigsuspend,
    // Sigpending,
    // Sigqueue,
    // SetGroups,
    // MemfdCreate,
    // Madvise,
    // PosixMadvise,
    // Msync,
    // GetItimer,
    // SetItimer,
    // TimerCreate,
    // TimerSettime,
    // TimerGettime,
    // TimerDelete,
    // TimerGetoverrun,
    // Times,
    Uname
// Pause,
// SetResuid,
// SetResgid,
// GetResuid,
// GetResgid,
// SetReuid,
// SetRegid,
// GetLoginR,
// IfIndextoname,
// IfNametoindex,
// Ptsname,
// Unlockpt,
// ThreadSetname,
// ThreadGetname,
// Sysconf,
// Semget,
// Semctl,
// GetAffinity,
// GetThreadaffinity,
// SetAffinity,
// SetThreadaffinity,
// GetCurrentStackInfo,
// Waitid,
// NameToHandleAt,
// Splice,
// Shmat,
// Shmctl,
// Shmdt,
// Shmget,
// InetConfigured,
// Nice,
// Openpt,
// Msgctl,
// Msgget,
// Msgrcv,
// Msgsnd,
// MqOpen,
// MqUnlink,
// MqReceive,
// MqGetAttr,
// MqSetAttr,

/* Linux sysdeps */
// InotifyCreate,
// InotifyAddWatch,
// InotifyRmWatch,
// Mount,
// Umount2,
// Ptrace,
// Capget,
// Capset,
// Prctl,
// InitModule,
// DeleteModule,
// Klogctl,
// Getcpu,
// Sysinfo,
// Swapon,
// Swapoff,
// Setxattr,
// Lsetxattr,
// Fsetxattr,
// Getxattr,
// Lgetxattr,
// Fgetxattr,
// Listxattr,
// Llistxattr,
// Flistxattr,
// Removexattr,
// Lremovexattr,
// Fremovexattr,
// Statfs,
// Fstatfs,
// Statx,
// Getifaddrs,
// Sendfile,
// Syncfs,
// Unshare,
// SetNs,
// PidfdOpen,
// PidfdGetpid,
// PidfdSendSignal,
// ProcessVmReadv,
// ProcessVmWritev,
// Fsopen,
// Fsmount,
// Fsconfig,
// MoveMount,
// OpenTree,
// CopyFileRange,

/* Linux epoll sysdeps */
// EpollCreate,
// EpollCtl,
// EpollPwait,

/* Linux timerfd sysdeps */
// TimerfdCreate,
// TimerfdSettime,
// TimerfdGettime,

/* Linux signalfd sysdeps */
// SignalfdCreate,

/* Linux eventfd sysdeps */
// EventfdCreate,

/* Linux reboot sysdeps */
// Reboot,

/* Linux wrappers sysdeps */
// RtSigqueueinfo,
// RtTgSigqueueinfo,

/* BSD sysdeps */
// Brk,
// GetLoadavg,
// Openpty,

/* GLIBC timerfd sysdeps */
// Personality,
// Ioperm,
// Iopl,
#ifdef __riscv
// RiscvFlushIcache,
#endif // __riscv
{
};

template <typename Tag>
using Sysdeps = SysdepOf<BadgerOSSysdepTags, Tag>;

} // namespace mlibc
