// vim: sw=4 et :
node {
    stage('Fetch sources') {
        dir('src') {
            dir ('mlibc') {
                checkout scm
                // don't replace sources
                writeFile file: 'checkedout.xbstrap', text: ''
            }
            sh 'cp mlibc/ci/bootstrap.yml .'
        }
    }
    docker.build('mlibc_cienv', 'src/mlibc/ci/docker').inside {
        dir('build') {
            stage('Prepare build') {
                sh '''#!/bin/sh
                set -xe
                xbstrap init ../src || true # no cleanWs() step
                '''
            }
            stage('Build mlibc') {
                sh 'xbstrap install --reconfigure mlibc'
            }
            stage('Install gcc') {
                sh 'xbstrap install-tool --recompile gcc'
            }
            stage('Collect results') {
                sh 'tar c system-root | xz - > root.tar.xz'
                archiveArtifacts 'root.tar.xz'
            }
        }
    }
}
