#ifndef __OBOS_VMA_H
#define __OBOS_VMA_H

#define __BIT(n) (1UL << (n))

typedef enum vma_flags
{
    VMA_FLAGS_HUGE_PAGE = __BIT(0),
    VMA_FLAGS_GUARD_PAGE = __BIT(2),
    VMA_FLAGS_32BIT = __BIT(3),
    VMA_FLAGS_HINT = __BIT(4),
    VMA_FLAGS_NON_PAGED = __BIT(5),
    VMA_FLAGS_PRIVATE = __BIT(6),
    VMA_FLAGS_PREFAULT = __BIT(7),
    VMA_FLAGS_32BITPHYS = __BIT(9),
    VMA_FLAGS_NO_FORK = __BIT(10),
    VMA_FLAGS_FRAMEBUFFER = __BIT(11),
    VMA_FLAGS_POSIX_COMPAT = __BIT(12),
    VMA_FLAGS_KERNEL_STACK = VMA_FLAGS_NON_PAGED|VMA_FLAGS_GUARD_PAGE,
} vma_flags;

typedef enum prot_flags {
	OBOS_PROTECTION_READ_ONLY = 0x1,
	OBOS_PROTECTION_EXECUTABLE = 0x2,
	OBOS_PROTECTION_USER_PAGE = 0x4,
	OBOS_PROTECTION_CACHE_DISABLE = 0x8,
	OBOS_PROTECTION_SAME_AS_BEFORE = 0x10,
	OBOS_PROTECTION_CACHE_ENABLE = 0x20,
	OBOS_PROTECTION_PLATFORM_START = 0x01000000,
	OBOS_PROTECTION_PLATFORM_END = 0x80000000,
} prot_flags;

#undef __BIT

#endif /* __OBOS_VMA_H */

