#pragma once

#define BIT(n) (1UL<<(n))

typedef enum vma_flags
{
    VMA_FLAGS_HUGE_PAGE = BIT(0),
    VMA_FLAGS_GUARD_PAGE = BIT(2),
    VMA_FLAGS_32BIT = BIT(3),
    VMA_FLAGS_HINT = BIT(4),
    VMA_FLAGS_NON_PAGED = BIT(5),
	VMA_FLAGS_PRIVATE = BIT(6),
	VMA_FLAGS_PREFAULT = BIT(7),
	VMA_FLAGS_RESERVE = BIT(8),
	VMA_FLAGS_KERNEL_STACK = VMA_FLAGS_NON_PAGED|VMA_FLAGS_GUARD_PAGE,
} vma_flags;
typedef enum prot_flags
{
	OBOS_PROTECTION_READ_ONLY = 0x1,
	OBOS_PROTECTION_EXECUTABLE = 0x2,
	OBOS_PROTECTION_USER_PAGE = 0x4,
	OBOS_PROTECTION_CACHE_DISABLE = 0x8,
	OBOS_PROTECTION_SAME_AS_BEFORE = 0x10,
	OBOS_PROTECTION_CACHE_ENABLE = 0x20,
	OBOS_PROTECTION_PLATFORM_START = 0x01000000,
	OBOS_PROTECTION_PLATFORM_END = 0x80000000,
} prot_flags;

#undef BIT
