#ifndef _ABIBITS_PTRACE_H
#define _ABIBITS_PTRACE_H


enum __ptrace_request {
    PTRACE_RESERVED,
    PTRACE_TRACEME = 5,             // Fixes an mlibc thing
    PTRACE_PEEKDATA,
    PTRACE_POKEDATA,
    PTRACE_GETREGS,
    PTRACE_GETFPREGS,
    PTRACE_GETREGSET,
    PTRACE_SETREGS,
    PTRACE_SETFPREGS,
    PTRACE_SETREGSET,
    PTRACE_GETSIGINFO,
    PTRACE_SETSIGINFO,
    PTRACE_PEEKSIGINFO,
    PTRACE_GETSIGMASK,
    PTRACE_SETSIGMASK,
    PTRACE_SETOPTIONS,
    PTRACE_GETEVENTMSG,
    PTRACE_CONT,
    PTRACE_SYSCALL,
    PTRACE_SINGLESTEP,
    PTRACE_SET_SYSCALL,
    PTRACE_LISTEN,
    PTRACE_KILL,
    PTRACE_INTERRUPT,
    PTRACE_ATTACH,
    PTRACE_SEIZE,
    PTRACE_DETACH,
    PTRACE_GET_SYSCALL_INFO,
};

enum __ptrace_event {
    PTRACE_EVENT_VFORK,
    PTRACE_EVENT_FORK,
    PTRACE_EVENT_CLONE,
    PTRACE_EVENT_EXEC,
    PTRACE_EVENT_EXIT,
    PTRACE_EVENT_STOP,
};

enum __ptrace_setoptions {
    PTRACE_O_TRACESYSGOOD           = 0x00000001,
    PTRACE_O_TRACEFORK              = 0x00000002,
    PTRACE_O_TRACEVFORK             = 0x00000004,
    PTRACE_O_TRACECLONE             = 0x00000008,
    PTRACE_O_TRACEEXEC              = 0x00000010,
    PTRACE_O_TRACEVFORKDONE         = 0x00000020,
    PTRACE_O_TRACEEXIT              = 0x00000040,
    PTRACE_O_EXITKILL               = 0x00000080,
    PTRACE_O_MASK                   = 0x000000FF
};

#endif