name: Rust libc bindings

on: [pull_request, merge_group]

jobs:
    check-bindings:
        name: Verify bindings generation
        runs-on: ubuntu-latest
        container: debian:trixie
        steps:
          - name: Install prerequisites
            run: |
                apt-get update
                apt-get install -y meson ninja-build \
                                python3-setuptools python3-jsonschema \
                                python3-pexpect python3-pip python3-clang \
                                netbase clang lld git rsync nodejs rustup
                pip install --break-system-packages -U xbstrap pyexpect
          - name: Prepare directories
            run: |
                mkdir src/
                mkdir src/mlibc/
                mkdir src/rust-libc/
                mkdir build/
          - name: Checkout
            uses: actions/checkout@v2
            with:
              path: src/mlibc/
          - name: Checkout rust-libc
            uses: actions/checkout@v4
            with:
              repository: 'rust-lang/libc'
              ref: '0.2.175'
              path: src/rust-libc
          - name: Prepare src/
            run: |
                cp mlibc/ci/bootstrap.yml .
                touch mlibc/checkedout.xbstrap
            working-directory: src/
          - name: Prepare build/
            run: |
              cat > bootstrap-site.yml << EOF
              define_options:
                arch: x86_64
                compiler: gcc
              EOF
              xbstrap init ../src
            working-directory: build/
          - name: Build mlibc
            run: 'xbstrap install mlibc-headers-only'
            working-directory: build/
          - name: Expand rust-libc sources
            run: |
                rustup toolchain install stable
                cargo install cargo-expand
                ~/.cargo/bin/cargo-expand expand unix > ../../build/libc-ignore.rs
                cd ../mlibc/scripts/libc-parser
                cargo run ../../../../build/libc-ignore.rs > ../../../../build/libc-ignore.yml
            working-directory: src/rust-libc/
          - name: Run generator
            run: |
                python3 ./scripts/rust-libc.py ../../build/packages/mlibc-headers-only/usr/include gcc -c ./scripts/rust-libc-config.yml ../../build/libc-ignore.yml | rustfmt
            working-directory: src/mlibc/

